### ISSUE TITLE
disable invoker tests if we are offline

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1065]
Without Internet connection our build fails, at the `invoker` step of `eo-maven-plugin`. Let's find a way to disable the entire invoker if we are offline.

**Comment by yegor256** [comment]
@mximp please, help here

**Comment by mximp** [comment]
@Karina5005 Could you please take it.

**Comment by Karina5005** [comment]
@mximp sure.
But can you give me more information, please.
Do I understand correctly that the problem is that when we run `mvn clean install` without an internet connection, an error occurs. And we want to solve this by disabling the steps that require an Internet connection?
I'm not sure that I understand correctly what "disable the entire invoker" means.

**Comment by mximp** [comment]
@Karina5005 We have `PullMojo` which requires remote connection for getting objects from Objectionary. It is executed during the build/tests. So we need to skip downloading if there is not connection. 
Please check `URL` usage in `eo-maven-plugin`.
I believe `PullMojo` should print a message that we are offline and do nothing.
Also please note that there tests in `eo-maven-plugin` which uses remote connection outside `PullMojo`.
