### ISSUE TITLE
Reusing `TransformerFactory.newInstance()`

### ISSUE THREAD

**Issue by IngeniariusSoftware** [objectionary/eo#1079]
@yegor256, I again got some result of profiling eo compiler 0.27.1 for about 500 eo files:

the total calling TransformerFactory.newInstance() by  counted for 36.31% of all CPU time and 29.39% of all memory allocations

It is possible to reuse TransformerFactory instance?

CPU:
![image](https://user-images.githubusercontent.com/33983579/186085489-458bf010-342c-461c-af80-7d0c3cfdfb8e.png)

Memory allocations:
![image](https://user-images.githubusercontent.com/33983579/186085507-a047daa6-5adb-4afd-a285-bc3b2451ecda.png)

**Comment by yegor256** [comment]
@IngeniariusSoftware how exactly do you run the test? What are you doing: parsing, optimizing, transpiling?

**Comment by IngeniariusSoftware** [comment]
@yegor256, I ran `mvn clean compile` and collected data from the beginning to the end of all the transformation steps. This is [the snapshot](https://drive.google.com/file/d/1hjO9GElLh5m0-uNDqq0xcssQWpE0c-iv/view?usp=sharing) that you can unpack and open via profiling intellij idea. Judging by the snapshot, the bulk of the calls `TransformerFactory.newInstance()` fall on `OptimizeMojo`

**Comment by yegor256** [comment]
@IngeniariusSoftware this indeed is very strange. We load all XSL documents statically -- only once per JVM. Why `newInstance()` is called so often -- I can't understand. Let's figure out and fix.

**Comment by yegor256** [comment]
@mximp please, help us here

**Comment by mximp** [comment]
@OlesiaSub please have a look

**Comment by OlesiaSub** [comment]
@yegor256 @IngeniariusSoftware 
If you look at the stack trace (below) you will see that the method `optimize` of `OptimizeMojo` calls `transformInto`, which calls `TransformerFactory factory = TransformerFactory.newInstance();`

Here is the beginning of `transformInto` method if you need it:
```
private void transformInto(XML xml, Result result) {
        Class var4 = XSLDocument.class;
        Transformer trans;
        synchronized(XSLDocument.class) {
            TransformerFactory factory = TransformerFactory.newInstance();
            ConsoleErrorListener errors = new ConsoleErrorListener();
            ...
```

As far as I understand the root of the problem is here. A new transformer factory is created every time `optimize` is called (or almost every time)

Stack trace:

![image](https://user-images.githubusercontent.com/57731693/186682518-765f7976-fb86-4889-bff8-d9dfbc999ded.png)

I can't think of a solution yet, because the cause is located somewhere deep in the stack trace and in external libraries (if I understood it correctly).

**Comment by yegor256** [comment]
@OlesiaSub it seems that you are right... let me think about it for a minute

**Comment by yegor256** [comment]
@OlesiaSub I [released](https://github.com/jcabi/jcabi-xml/issues/172) jcabi-xml 0.25.3, which caches `Transformer`. now, our Maven plugin works faster. on my Macbook instead of 6 minutes the entire build completes in 3 minutes. @IngeniariusSoftware many thanks for the hint!

**Comment by yegor256** [comment]
@rultor release, tag is `0.27.2`
