### ISSUE TITLE
data.xsl:26-29: This code tests for both org.eolang.TYPE...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1111]
The puzzle `1104-f29eb2d4` from #1104 has to be resolved: 

https://github.com/objectionary/eo/blob/31138081b224666d5790908db65df659d4aeafd9/eo-maven-plugin/src/main/resources/org/eolang/maven/pre/data.xsl#L26-L29

The puzzle was created by @rultor on 29-Aug-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@mximp please, help us resolve this

**Comment by mximp** [comment]
@OlesiaSub could you please have a look

**Comment by OlesiaSub** [comment]
I have an explanation but I don't have a good solution yet.
@yegor256 @mximp please have a look.

Let's take a look at this piece of code located in your `bool.eo` file
```
# NOT
[] > not
  eq. > @
    ^
    FALSE
```
We are particularly interested in usage of `FALSE`.
In transpiled `.xmir` `FALSE` will look like this:
```
&lt;o base="bool" data="bytes" line="43" pos="6" ref="29"&gt;00&lt;/o&gt;
```
Note that it has a `ref` attribute because it's abstract object `bool` is located in the same file (bool.eo).
But `add-default-package.xsl` reasonably does not add default packages to the objects with `ref` attributes, so in all cases like this default package won't be added.

Same situation occurs when we use numbers representing `int` in `int.eo` file, etc. It does not occur in any other cases, so maybe removing this `TYPE` checks is not necessary?

**Comment by mximp** [comment]
@yegor256 @OlesiaSub This corresponds to the the description in `add-default-package.xsl`:
```
  <!--
  Here we go through all objects that DON'T have @ref attributes
  and add default package to them.

  We ignore objects that are present in aliases with their exact
  names. For example, this object 'hello' won't be touched, we
  won't think that it belongs to org.eolang package:

  +alias hello
  [] > app
    hello > @
  -->
```
So it looks like current behaviour is in line with common logic. 
I can't think of any solution for fixing it rather than hardcode specific logic for data types in `add-default-package.xsl`, but I don't think it's worth to do.
I suggest to keep it as is.

**Comment by mximp** [comment]
@yegor256 Can we remove the puzzle and close it as "won't fix?"

**Comment by yegor256** [comment]
@mximp sure, we just need to submit a pull request that removes the puzzle

**Comment by mximp** [comment]
@OlesiaSub please do

**Comment by 0pdd** [comment]
The puzzle `1104-f29eb2d4` has disappeared from the source code, that's why I closed this issue.
