### ISSUE TITLE
rust.eo:29-33: Complete implementation of this object in...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1326]
The puzzle `1161-bdee702e` from #1161 has to be resolved: 

https://github.com/objectionary/eo/blob/cd3465dfb99b6daee240c32931b87e4f60501343/eo-runtime/src/main/eo/org/eolang/rust.eo#L29-L33

The puzzle was created by rultor on 09-Oct-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by levBagryansky** [comment]
Now we are going to create new method every time we meet a new `insert` in runtime stage. According to 
https://www.quora.com/How-can-I-dynamically-create-a-Java-class-and-execute-its-methods-at-runtime
and https://stackoverflow.com/questions/6680674/can-a-java-class-add-a-method-to-itself-at-runtime we can't just create a new method. Instead, we have to recreate and reload the class with methods every time we encounter a new `rust insert` for which a function has not yet been generated.
I guess we can generate this class only once, at the compilation stage. since we know all the "rust" inserts before runtime, which means we can generate a new java class, just as we generate them from eo objects. So I suggest generating "EOrust.java" somewhere at the parsing stage, where other java files are generated. This would make it possible to lighten the load in runtime due to compilation. 
@yegor256 @Graur WDYT?
I want to check the mechanism on my prototype.

**Comment by yegor256** [comment]
@yegor256 I didn't understand the question. If you submit a prototype in a PR, it will be easier to review it.

**Comment by volodya-lombrozo** [comment]
@levBagryansky Is that issue solved? Do we need to continue here?

**Comment by levBagryansky** [comment]
@volodya-lombrozo yes, it relates to rust inserts

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#2031](https://github.com/objectionary/eo/issues/2031), [#2032](https://github.com/objectionary/eo/issues/2032), [#2033](https://github.com/objectionary/eo/issues/2033) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#2032](https://github.com/objectionary/eo/issues/2032), [#2033](https://github.com/objectionary/eo/issues/2033) are still not solved; solved: [#2031](https://github.com/objectionary/eo/issues/2031).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#2033](https://github.com/objectionary/eo/issues/2033) is still not solved; solved: [#2031](https://github.com/objectionary/eo/issues/2031), [#2032](https://github.com/objectionary/eo/issues/2032).
