### ISSUE TITLE
SynchronizedTojo.java:31-34: Replace this custom {@link...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#1337]
The puzzle `1230-0c34d341` from #1230 has to be resolved: 

https://github.com/objectionary/eo/blob/2fd90f407b6a33a8679a8575314d9659932d968e/eo-maven-plugin/src/main/java/org/eolang/maven/SynchronizedTojo.java#L31-L34

The puzzle was created by rultor on 14-Oct-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by mximp** [comment]
This can be implmented since https://github.com/yegor256/tojos/issues/16 is fixed.

**Comment by mximp** [comment]
@volodya-lombrozo please assist

**Comment by volodya-lombrozo** [comment]
Current issue is blocked by other [issue](https://github.com/yegor256/tojos/issues/39). We need to implement a thread safe `Mono` decorator in order to solve concurrency problem and remove `SynchronizedTojo` from `eo`.
I've just implemented the concurrency test for parsing mojo in order to prove the problem.

**Comment by volodya-lombrozo** [comment]
@mximp Can you reopen the issue, please? it haven't finished yet. (Rulter closed the issue occasionally)
