### ISSUE TITLE
`!` does not avoid recall

### ISSUE THREAD

**Issue by ivan-egorov42** [objectionary/eo#1353]
As it seems there is a recall of function `f` in the object `lib-obj` in this simple example:
```
+alias org.eolang.txt.sprintf
+alias org.eolang.io.stdout

[] > app
  lib-obj > @
    [i]
      stdout > @
        sprintf
          "Here is my call with number %d\n"
          i

[f] > lib-obj
  seq > @
    f > acc1!
      1
    f > acc2!
      2
    if.
      eq.
        acc1
        acc2
      stdout
        sprintf
          "All is OK\n"
      stdout
        sprintf
          "Smth is bad\n"
```
Here is output:
```
Here is my call with number 1
Here is my call with number 2
Here is my call with number 1
Here is my call with number 2
All is OK

```
As you can see program calls `f` 4 times instead of 2. 
Is it OK or `!` should prevent it?

**Comment by ivan-egorov42** [comment]
@Graur @mximp please, have a look.

**Comment by ivan-egorov42** [comment]
Mb, it is according to #1299, but I'm not sure. The problem is still actual.

**Comment by includealex** [comment]
@ivan-egorov42 I think that it works correctly. Slight modification of your program will make your program work as you want.
```eo
+alias org.eolang.io.stdout
+alias org.eolang.txt.sprintf

[] > app
  lib-obj > @
    [i]
      stdout > @
        sprintf
          "Here is my call with number %d\n"
          i

[f] > lib-obj
  f > a!
    1
  f > b!
    2
  seq > @
    if.
      eq.
        a
        b
      stdout
        sprintf
          "All is OK\n"
      stdout
        sprintf
          "Smth is bad\n"

```

**Comment by includealex** [comment]
@ivan-egorov42 Why does your program give double printage? The reason is that `seq` dataizes it's every argument. If you take a look to your code, you will find out that `seq` runs 3 steps:

1. Dataizes `acc1`, thus it prints
```bash 
Here is my call with number 1
```
2. Dataizes `acc2`, prints 
```bash
Here is my call with number 2
```
3. Goes to `eq` object, then it will try to find out, what do `acc1` and `acc2` are equal to. It tries to copy objects `acc1.eq` and `acc2.eq` . To do it, `seq` starts to go through inside `acc1` function, and that is why `stdout` is called for the second time:
```bash
Here is my call with number 1
Here is my call with number 2
```

**Comment by ivan-egorov42** [comment]
@includealex thanks!)
