### ISSUE TITLE
`Footprint` design. `load()` method is redundant

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1420]
The `Footprint` interface has the next declaration:
```java
interface Footprint {

    String load(String program, String ext) throws IOException;

    void save(String program, String ext, Scalar<String> content) throws IOException;
}
```
If you take a look closely, the method `load()` is used only in the class `FtCached` (that is an implementation of `Footprint`). It means we can remove method `load()` from `Footprint` class at all.

**Comment by mximp** [comment]
@volodya-lombrozo That's correct: at the moment `Footprint.load()` isn't used from client code. But that's because EO programs' files are accessed via paths directly in different build phases (e.g. `OptimizeMojo`).  The only place we are using `Footprint` now is `ParseMojo`.
The idea of `Footprint` is to provide abstraction for EO program files content. For that we need both `save` and `load` methods.
I would say that we rather need tasks for leveraging `Footprint` in all other places (where applicable) in which we are accessing program files. The marker could be usage of `Place` class: in all such places would probably want to use `Footprint` as well.

**Comment by volodya-lombrozo** [comment]
@mximp what about `Home` class then? It's an abstraction for EO program files content too.

**Comment by mximp** [comment]
> @mximp what about `Home` class then? It's an abstraction for EO program files content too.

@volodya-lombrozo Not exactly. `Home` doesn't imply any specific content of files. Its key feature is fixed base path and then you can operate with files relative to that path. 
On the other hand `Footprint` encapsulates EO program specifically. It forms paths based on program name. Moreover `Footprint` can operate on several files (e.g. cached implementation) simultaneously. I would say that `Footprint` can/should leverage `Home` functionality.

**Comment by volodya-lombrozo** [comment]
Why then it has a name `Footprint` instead of `EoProgram`? `Footprint` is a quite confusing naming, as for me.

**Comment by volodya-lombrozo** [comment]
@mximp your words make it clear. Thank you. Maybe we can put them into `JavaDoc`, what do you think?
As for `load()` method - we might use it or delete, because for now it's looks like overdesign.

**Comment by mximp** [comment]
@volodya-lombrozo Currently javadoc says: "Program footprint of EO compilation process". It's a pure rephrase of what I said above. 
I believe the confusion is in the meaning of word `footprint` which is not used quite often in everyday speech by non-natives. [Cambridge dictionary](https://dictionary.cambridge.org/dictionary/english/footprint) suggests good definition of it: _a measurement of the size, effect, etc. that something has_

**Comment by yegor256** [comment]
@volodya-lombrozo @mximp what's up with this? We should close or do some changes to the code?

**Comment by mximp** [comment]
@volodya-lombrozo I suggest to close this one.
