### ISSUE TITLE
rewrite GOTO in EO, using TRY object

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1562]
I think it's possible to remove Java from the `goto` atom and rewrite it in pure EO, using the `try` atom. Let's try.

**Comment by yegor256** [comment]
@mximp please, help here

**Comment by mximp** [comment]
blocked by #1570

**Comment by mximp** [comment]
@yegor256 simple implementation (in draft PR) implies couple of limitations:
1. nested goto's are not allowed
2. since `goto` relies on `while` it performs additional dataization which is not always intuitively clear and need to be taken into account.

At the moment I cannot find a way to implement EO version of `goto` without using `bool.while`. Also I couldn't find a way to overcome above limitations. It seems that it would require much more complex code in EO (if even possible).

So the question is: are we ok with those limitations of `goto`?.
Otherwise I would suggest to leave `goto` as an atom.

**Comment by mximp** [comment]
This task is blocked until the way is found to avoid double dataization.
