### ISSUE TITLE
The injector of eo-runtime ignores the presence of it

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#1589]
Check this commit: b199643f

Without this line:

```
<withRuntimeDependency>false</withRuntimeDependency>
```

The dependency version is taken from Maven Central (check the logs of Maven Invoker Plugin), while `1.0-SNAPSHOT` should be used, since it's explicitly specified in the `pom.xml`.

**Comment by yegor256** [comment]
@volodya-lombrozo would be great to fix it ASAP, since it blocks the releases of other packages

**Comment by yegor256** [comment]
@volodya-lombrozo I would also remove `withRuntimeDependency` to `addRuntimeDependency`

**Comment by volodya-lombrozo** [comment]
@yegor256 I was struggling with the current issue and I don't understand the proper solution. Statements about current compilation and dataization pipeline:
1. We use `eo-maven-plugin` up to `transpile` phase (creating of Java Classes)
2. Next we use `compile` plugin to compile `java` to `bytecode`
3. Next we use `jar` plugin to package thin `jar` (without any dependencies)
4. Next we use `java -jar ...` to `dataize` the program

In order to make `java -jar ...` works correctly, `jar` has to contain `eo-runtime` library classes. Since we compile thin jar without dependencies, the "pulling" of classes has to be done on `ResolveMojo` and `PullMojo` stages. In other words, our `eo-maven-plugin` pulls `eo-runtime` classes on `assembly` stage (1 step). And it's the reason why our final `jar` already contains them.

The problem:
If you add `eo-runtime` dependency to the `dependencies` section - it doesn't work and shouldn't (because we run `java -jar ...` without providing classpath)


Please, correct me if I'm wrong.

**Comment by volodya-lombrozo** [comment]
@yegor256 Why should we scan "dependencies" section?

**Comment by volodya-lombrozo** [comment]
@yegor256 Can we close the issue?

**Comment by volodya-lombrozo** [comment]
@yegor256 Reminder

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1673](https://github.com/objectionary/eo/issues/1673) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#1673](https://github.com/objectionary/eo/issues/1673) is solved here.
