### ISSUE TITLE
prohibit "sparse" decoration

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#2109]
I found it here: https://github.com/objectionary/eo-collections/blob/e6f761879d5b6f9c9f3fc54671a568e8d7dad2a2/src/main/eo/org/eolang/collections/range.eo#L45-L63 (@maxonfjvipon correct me if I'm wrong). I think we should prohibit such structures:

```
[] > a
  [] > @
    42 > test
```

We must demand users to do this instead, because semantically it's exactly the same:

```
[] > a
  42 > test
```

Thus, "sparse decoration" (it decorates an object but doesn't add anything to it) must be prohibited by an XSL validation step.

**Comment by yegor256** [comment]
@maxonfjvipon can you help?

**Comment by maxonfjvipon** [comment]
@yegor256 I believe that:
```
[] > a
  42 > test
```
It's not really the same as
```
[] > a
  [] > @
    42 > test
```

As for me these examples are not clear a bit. Let's take object `range` from `eo-collections`. 

1. These lines: https://github.com/objectionary/eo-collections/blob/e6f761879d5b6f9c9f3fc54671a568e8d7dad2a2/src/main/eo/org/eolang/collections/range.eo#L48-L55
```
if. > @
  current.lt last
  []
    append > @
      ...
  acc
```

Here I agree that it can (and probably must) be replaced with:
```
if. > @
  current.lt last
  append
    ...
  acc
``` 

2. These lines: https://github.com/objectionary/eo-collections/blob/e6f761879d5b6f9c9f3fc54671a568e8d7dad2a2/src/main/eo/org/eolang/collections/range.eo#L45-L63
```
[start end] > range
  [] > @
    [acc current last] > append
      ...

    if. > @
      ...
```

Here I believe that there's nothing wrong with the abstract object because we don't want `append` object be child of `range` object so user won't be able to "call" it.

If we image something like this:
```
[start end] > range
  [acc current last] > append
    ...
  if. > @
    ...
```
In such case I think I can do `(range 1 10).append ...` which is kind of wrong. So we hide `append` object from the user here.

My conclusion is that we should enforce users to not create abstract objects in cases like 1. But case 2 makes sense. WDYT?

**Comment by maxonfjvipon** [comment]
@yegor256 Yes, I was wrong about "hiding".

> Thus, "sparse decoration" (it decorates an object but doesn't add anything to it) must be prohibited by an XSL validation step.

What do you mean "it decorates an object does not add anything to it"? In case 2 object `range` is decorator of an abstract object which is decorator of object `if` => `range` is decorator of `if`. I quite don't understand how object `range` can add something to `if`. Does it count that object `append` was added inside an abstract object?

**Comment by yegor256** [comment]
@maxonfjvipon this is "sparse" decoration:

```
[] > a
  b > @
```

The object `a` decorates `b`, but doesn't add any new attributes to it. So, semantically `a == b` (they behave exactly the same).

Here, on the other hand, `a` _adds_ new attribute `c` to the `b` object:

```
[] > a
  b > @
  42 > c
```

**Comment by yegor256** [comment]
@maxonfjvipon I would put it right before `"/org/eolang/parser/warnings/unsorted-metas.xsl"`

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#2161](https://github.com/objectionary/eo/issues/2161) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#2161](https://github.com/objectionary/eo/issues/2161) is solved here.
