### ISSUE TITLE
Unintuitive comparison in `ForeignTojos.contains()`method

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo#2213]
Here in [`ForeignTojos`](https://github.com/objectionary/eo/blob/a42310f616667990e80f830295f8f1b07343d050/eo-maven-plugin/src/main/java/org/eolang/maven/tojos/ForeignTojos.java#L182) we have method `contains()` that looks like this.

```java
/**
 * Check if the tojos contains a foreign tojo with name.
 * @param name The name of the tojo.
 * @return True if the tojo exists.
 */
public boolean contains(final String name) {
    return this.select(tojo -> tojo.get(Attribute.ID.key()).equals(name)).isEmpty();
}
```
I don't understand why it returns the result of `isEmpty()` method. I read it like this: "select tojos where id equals to name => check if they are empty"

@volodya-lombrozo could you please explain?

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Let's break that code by pieces:
1. `this.select(...)` returns the `Collection` of `ForeignTojo` objects.
2. `this.select(...).isEmpty()` checks if the collection that we get on (1) step is empty
3. `tojo -> tojo.get(Attribute.ID.key()).equals(name)` - is the lambda expression that returns `true` if `ForeignTojo` id equals `name`, false otherwise. Consider that lambda as "filter" that checks each element in the collection.
4. `tojo.get(Attribute.ID.key()).equals(name)` - the id of `ForeignTojo` is actually its name (which is rather weird, I know)

So, we are just trying to find all foreign tojos which "id" == "name" and if we find any - we return `true`

If something is still unclear, do not hesitate to ask

**Comment by yegor256** [comment]
@maxonfjvipon @maxonfjvipon would be much better to turn this explanation into a Javadoc documentation, to avoid similar questions in the future, see https://www.yegor256.com/2015/02/16/it-is-not-a-school.html

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon I've understood your concern here. We call that method only once:
```java
if (!this.scopedTojos().contains(name)) {
    Logger.debug(this, "EO source %s already registered", name);
    continue;
}
```
Which works fine, but actually has a grammar mistake. We have to either rename method to `notContains`, or just add inversion:
```java
public boolean contains(final String name) {
   !return this.select(tojo -> tojo.get(Attribute.ID.key()).equals(name)).isEmpty();
}
```
and remove inversion from the caller code:
```java
if (this.scopedTojos().contains(name)) {
    Logger.debug(this, "EO source %s already registered", name);
    continue;
}
```

Moreover, it would be great to add unit test for that method.

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Could you help us here please?

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo sure, please assign me

**Comment by 0pdd** [comment]
@maxonfjvipon the puzzle [#2220](https://github.com/objectionary/eo/issues/2220) is still not solved.

**Comment by 0pdd** [comment]
@maxonfjvipon the only puzzle [#2220](https://github.com/objectionary/eo/issues/2220) is solved here.
