### ISSUE TITLE
OptCached.java:40-44: Unify caching mechanism on stages:...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo#2822]
The puzzle `2746-0e77f2c4` from #2746 has to be resolved: 

https://github.com/objectionary/eo/blob/99ed421b3d855afe6a55c2b0f97dae824dc4549b/eo-maven-plugin/src/main/java/org/eolang/maven/optimization/OptCached.java#L40-L44

The puzzle was created by rultor on 26-Jan-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by Yanich96** [comment]
@maxonfjvipon assign me , please

**Comment by Yanich96** [comment]
At this moment `ParseMojo` has bug in cache: loading from cache does not work correctly.
For example: 
We have program named `main.eo`. After the first execution of this program, its result will be saved in cache `ParseMojo`. But changes will be done in `main.eo` after the first execution, we will get the result of the first program.
This happens because at the `ParseMojo` stage, verification of the file in the cache occurs only in the plugin version and file name.

**Comment by 0pdd** [comment]
The puzzle `2746-0e77f2c4` has disappeared from the source code, that's why I closed this issue.
