### ISSUE TITLE
upgrade qulice to 0.22.2

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#2937]
Let's upgrade it to 0.22.2: there are many fixes to be made, but they are not hard to make.

**Comment by yegor256** [comment]
@c71n93 maybe you can help?

**Comment by c71n93** [comment]
@yegor256 Ok, I will take it

**Comment by c71n93** [comment]
@yegor256 There are A LOT OF warnings, that says: "JUnit assertions should include a message". The problem is, that in most of tests we don't have assertion messages. It is impossible to write an informative message to every assertion in an adequate amount of time. I see 2 options here:
1. Suppress this warnings in all test methods (maybe add todo).
2. Add stub messages like "" or "Message".
@yegor256 WDYT?

**Comment by yegor256** [comment]
@c71n93 it's better to add meaningful messages, as much as possible
