### ISSUE TITLE
Untestable API 

### ISSUE THREAD

**Issue by l3r8yJ** [objectionary/eo#3088]
`TranspileMojo` have this private method `#cleanUpClasses`, which is extremely hard to test, because it's private, obviously

https://github.com/objectionary/eo/blob/d3caa91541b57a7f6b5ef7c71f11f1037e15c7a4/eo-maven-plugin/src/main/java/org/eolang/maven/TranspileMojo.java#L269-L287

my suggestion is to create a separate class instead of `private` method, which will resolve same problem. Class can be moved to another repo or it can be placed inside of EO

@maxonfjvipon @volodya-lombrozo wdyt?

**Comment by maxonfjvipon** [comment]
@l3r8yJ sounds good for me

**Comment by l3r8yJ** [comment]
@maxonfjvipon assign me please

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon @l3r8yJ, I have some doubts about this method. Actually, this is a crutch that we added to hide a problem with "unexpected" classes that were added during compilation:

> Some libraries by mistake can put ALL their compiled classes right into the final library jar, instead of only adding atoms.

Therefore, I believe that we should solve the original problem instead of adding tests that we will remove as soon as we solve the problem.

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo I think we'll face this problem again while implementing #1602. Imagine you have two versioned objects from different libraries `QQ.txt.sprintf|0.1.0` and `QQ.files.dir|0.2.0` and they both needs their own `eo-runtime`. It may be the same version of runtime, may be different. And I'm not sure how it should be resovled.
For now we have two tickets: bad API and no concurrency test. Let's implement it for now.

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon, this is exactly what I mentioned above: we don't know how to solve the **original** problem:

>   And I'm not sure how it should be resovled. 

Let's then concentrate on this problem instead of implementing the code that we will remove immediately when we actually do solve the problem.

As for this:

> For now we have two tickets: bad API and no concurrency test. 

I have no idea what exactly you mean; could you provide some links, please? Especially to the **bad API** ticket. Which API are you referring to?

Again, I believe that we should solve the original problem instead of adding tests that we will remove as soon as we solve the problem. But of course, if you enjoy beating around the bush, I can't you stop here :)

**Comment by l3r8yJ** [comment]
@maxonfjvipon to be honest, I completely agree with @volodya-lombrozo, in such cases there is no point in doing such work. I think we need to work smarter, not harder; and focus on the root cause of the problem

wdyt?

**Comment by maxonfjvipon** [comment]
@l3r8yJ as you wish. Then I suggest at least to replace "wrong" tickets and puzzles with "right" ones which would explain what we actually need to do and when it'll be possible

**Comment by l3r8yJ** [comment]
@maxonfjvipon okay
