### ISSUE TITLE
eo benchmarks

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#3127]
It can be useful to measure eo performance in future. I think it can be looked like this:
By analogy with `+tests` we can add `+benchs` to eo files.
Such files should be translated to java benchmakrs:
```java
public final class EOadd_testTest extends PhDefault {  
...
public static class MyBench {      
  @Benchmark  
  @OutputTimeUnit(TimeUnit.NANOSECONDS)   
  @BenchmarkMode(Mode.AverageTime)   
  @Fork(value = 1, warmups = 1 )   
  @Warmup(iterations  = 2)  
  public static void works(final Blackhole blackhole) throws java.lang.Exception {  
    blackhole.consume(new Dataized(new EOrust_find_returns_int_0Test()).take());  
  }  
}

}
```
and run by `mvn clean install -Pbench`. 
In addition we can add similar command to eoc like `eoc bench <EO object>` . This will generate java class with benchmark calls to dataization of EO class and run it.

**Comment by yegor256** [comment]
@maxonfjvipon @volodya-lombrozo what do you think about this?

**Comment by volodya-lombrozo** [comment]
@yegor256 It makes sense to add some sort of benchmark in EO. However, I'm not sure about the suggested implementation. Maybe it's safe (and simpler) to implement something our own. Some simple, straightforward solution for benchmarking, instead of relying on [JMH](https://github.com/openjdk/jmh) framework. At least for now, we don't need such a sophisticated tool. 
Moreover, I'm not sure if "benchmarking" should be a part of `objectionary/eo`.

**Comment by yegor256** [comment]
fixed
