### ISSUE TITLE
Validate distribution of sequence generated by random

### ISSUE THREAD

**Issue by mximp** [objectionary/eo#817]
Test that random sequence corresponds to normal distribution.

Random generation is implemented as part of #791.

**Comment by yegor256** [comment]
@mximp deal with this pls

**Comment by mximp** [comment]
@potatmen Can you please help with this.

**Comment by potatmen** [comment]
@mximp sure

**Comment by potatmen** [comment]
@mximp did you mean uniform distribution? Because the probability of getting any of the values should be equal. 
Also, according this ![histogram](https://user-images.githubusercontent.com/90863441/183903734-c5a6a71c-b1ed-4191-8715-cb96be8c59eb.png) for 100000 random values we can see a uniform distribution.

**Comment by mximp** [comment]
@potatmen that's right - uniform distribution is desired here.
Could you please also attach the file with generated values (any form).

**Comment by potatmen** [comment]
@mximp here is more accurate histogram
![Hist](https://user-images.githubusercontent.com/90863441/183909138-3d3bce4c-0be0-4a49-a386-ea1ec47a59a4.png)
Here is generated data
[Data](https://github.com/objectionary/eo/files/9300268/res.txt)
Btw, I can create a repository with source code and generated data.

**Comment by mximp** [comment]
@potatmen that's not required.

Thanks for your help!
