### ISSUE TITLE
`replace` in the `string` and `regex`

### ISSUE THREAD

**Issue by IngeniariusSoftware** [objectionary/eo#865]
It would be great to have variation of [replace](https://www.geeksforgeeks.org/java-lang-string-replace-java/) attributes in the [string](https://github.com/objectionary/eo/blob/master/eo-runtime/src/main/eo/org/eolang/string.eo) or/and [regex](https://github.com/objectionary/eo/blob/master/eo-runtime/src/main/eo/org/eolang/txt/regex.eo) objects.

**Comment by yegor256** [comment]
@mximp let's discuss and implement this

**Comment by mximp** [comment]
Let's introduce new object within `org.eolang.txt` defined as follows:
```
+package org.eolang.txt
+alias org.eolang.txt.regex

[s e r] > replace
  <replace logic> > @
```
where:  
  `s` -  base string to replace in; 
  `e` - is a string with regexp to search for; 
  `r` - string to replace with.

`replace` would decorate EO `string` object. 
Logically It will be equivalent to Java `String.replaceAll()`: replace all found matches within `s` to `r`.
Internally `replace` would use `org.eolang.txt.regex`.

The usage would be as follows:
```
+alias org.eolang.txt.replace

[] > app
  stdout > @
    replace
      "Object Oriented Programming"
      "/(object oriented programming)/i"
      "Elegant Objects"
```

Such form of replace must cover most of substitution use cases.

**Comment by mximp** [comment]
@yegor256 what do you think regarding above?

**Comment by yegor256** [comment]
@mximp can you make an example with a number of replacements and also with substitutions: https://docs.microsoft.com/en-us/dotnet/standard/base-types/substitutions-in-regular-expressions

**Comment by mximp** [comment]
@yegor256 please check now

**Comment by mximp** [comment]
@yegor256 That's an option.

I was thinking: how would one chain replacements if need two or more?
Having your suggestion:
```
replaced.
  QQ.txt.regex
     "/(123)/"
     replaced.
       QQ.txt.regex
          "/(ABC)/"
        "ABC123"
        "abc"
     "456"
```
With my proposal:
```
replace
  replace
    "ABC123"
    "/(ABC)/"
    "abc"
  "/(123)/"
  "456"
```
Second one seems to be less verbose and more clear.

**Comment by yegor256** [comment]
@mximp the problem with your code is that there is no place for the "compiled" step. There is `compile` method in `regex` object, which prepares the regex for further processing. In my case:

```
replaced.
  compile.
    QQ.txt.regex
       "/(123)/"
       replaced.
         compile.
           QQ.txt.regex
              "/(ABC)/"
            "ABC123"
            "abc"
       "456"
```

**Comment by mximp** [comment]
@yegor256 don't you think hiding `compile` step within `replace` (or `replaced`) functionality would simplify usage?

In you suggestion I would at least swap arguments: input string and replace pattern. This will make the latter closer to regexp  which may be referenced in it (via `$`).

**Comment by mximp** [comment]
Let's introduce new attribute within `org.eolang.txt.regex` defined as follows:
```
[s r] > replaced
  <replace logic> > @
```
where:  
  `s` - input string to replace in; 
  `r` - replacement pattern string.

`replaced` would decorate EO `string` object. 
Logically It will be equivalent to Java `String.replaceAll()`: replace all found matches within `s` to `r`.
Replacement pattern `r` may contain special characters which are:
`$n` - reference to capturing group _n_
`${gn}` - reference to named capturing group with name _gn_

Such form of replace must cover most of substitution use cases.

### Usage examples

**Simple literal replacement:**
```
[] > app
  stdout > @
    replaced.
      compile.
        regex "/(object oriented programming)/i"
      "Object Oriented Programming"
      "Elegant Objects"
```
Output:
```
"Elegant Objects3"
```

**Referencing capture group in replacement string**
```
[] > app
  stdout > @
    replaced.
      compile.
        regex "/((([A-Za-z])[0-9])\g{2})/"
      "a1a A2B B3B"
      "$2"
```
Output:
```
"a1 A2B B3"
```
Here `$2` in the replacement pattern will refer to the second capturing group which is defined by `(([A-Za-z])[0-9])` hence matching substrings (`a1a` and `B3B`) will be replaced with two symbols each.

**Referencing named capture group in replacement string**
```
[] > app
  stdout > @
    replaced.
      compile.
        regex "/((?<cpt>([A-Za-z])[0-9])\g{2})/"
      "a1a A2B B3B"
      "${cpt}"
```
Output:
```
"a1 A2B B3"
```
Same as above but we reference group by name `cpt` in replacement pattern rather than by index.

**Replacing `$` character**
```
[] > app
  stdout > @
    replaced.
      compile.
        regex "/(\\$)/"
      "Ma$trix"
      "\\$\\$"
```
Output:
```
"Ma$$trix"
```
In this case `$` needs to be escaped both in matching regexp and in replacement pattern.

**Comment by mximp** [comment]
@yegor256 renewed the induction

**Comment by mximp** [comment]
@yegor256 any objection we proceed implementation according to latest comment?

**Comment by yegor256** [comment]
@mximp looks good now, let's implement!

**Comment by mximp** [comment]
@IngeniariusSoftware @yegor256 This is implemented and can be closed.
Next step: #930
