### ISSUE TITLE
.catalog() in PlaceMojo and in ad-hoc catalog in UnplaceMojo

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#998]
Both PlaceMojo and UnplaceMojo don't use `CachedTojos`. I suggest we fix this by making them use it. Probably, we should make a new protected method `placeCatalog()` in `SafeMojo` and let both mojos use it.

**Comment by yegor256** [comment]
@mximp please, take care of this

**Comment by mximp** [comment]
@OlesiaSub Can you please help with this

**Comment by mximp** [comment]
**_Implementation notes_**: this can be implemented similarly to `SafeMojo.tojos`.

**Comment by OlesiaSub** [comment]
@mximp I'm not sure I fully understand the problem and the desired solution.
As far as I understood, the problem is that both PlaceMojo and UnplaceMojo always just create a new catalog and don't cache it?
And I need to create a method to cache the catalog. But the created catalog depends on parameters `placed` and `placedFormat`, for example PlaceMojo has this method:
```
    private Tojos catalog() {
        return new Catalog(this.placed.toPath(), this.placedFormat).make();
    }
```
Is the assumption that these two parameters are instantiated only once in the beginning of the execution correct and can I rely on it?

**Comment by mximp** [comment]
@OlesiaSub `placed` and `placedFormat` are the property of the plugin goal. They are set only once and don't change during maven run execution.
`placed` catalog has the same behaviour as `foreign`. It just happened that `foreign` has been implemented in `SafeMojo`.
So I would suggest to move `placed` and `placedFormat` props to `SafeMojo` and create `placedTojos` protected field (as suggested by Yegor).

**Comment by mximp** [comment]
@yegor256 done!

**Comment by yegor256** [comment]
@OlesiaSub @mximp thanks!
